### ISSUE TITLE
Find a way to keep track of downloaded files without keeping them on disk

### ISSUE THREAD

**Issue by gabek** [gabek/samcloud-updater#5]
Right now the `downloads` directory is what is checked to determine if we should download a new file or not (https://github.com/gabek/samcloud-updater/blob/master/utils.go#L54).  We need something lightweight to check so these files can be deleted immediately and not kept for the long term.

Maybe use something like https://github.com/GitbookIO/diskache to just save a hashed string of the url in the cache, and check for the existence of that key.

**Comment by RPiAwesomeness** [comment]
I'm up for giving this a go!

**Comment by gabek** [comment]
@RPiAwesomeness Awesome!  (No pun intended).  Thanks for looking into this!  Do you actually have an internet radio station, or just looking to contribute?  Just curious :)

**Comment by RPiAwesomeness** [comment]
@gabek Just looking to contribute. I'm wondering if that's going to be an issue now, after reading over the code a bit more.

**Comment by gabek** [comment]
I _think_ it should be as straightforward as replacing how it currently decides if a file should be downloaded (by checking if it's on the filesystem https://github.com/gabek/samcloud-updater/blob/master/utils.go#L54) with something like `FileHasDownloaded` and then check some kind of cached record of downloads.  Or that's my thought, anyway!
